# Generated by Django 4.2 on 2023-04-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='order_reference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza', to='ors.order'),
        ),
    ]
