# Generated by Django 4.2 on 2023-04-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_remove_order_pizza_pizza_order_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_info',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default='Null'),
        ),
    ]
