# Generated by Django 4.2 on 2023-04-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0003_rename_customer_info_order_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='total_price',
        ),
    ]
