# Generated by Django 4.2 on 2023-04-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0004_rename_customer_id_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='order_reference',
            new_name='order',
        ),
    ]
