# Generated by Django 4.2 on 2023-04-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0006_remove_rating_customer_remove_rating_deliveryman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='message',
            field=models.CharField(blank=True, default='Sin mensaje', max_length=200),
        ),
    ]
