# Generated by Django 4.2 on 2023-04-30 19:39

import apps.ors.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0007_alter_rating_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cedula',
            field=models.PositiveIntegerField(validators=[apps.ors.validators.validate_cedula]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[apps.ors.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='cedula',
            field=models.PositiveIntegerField(validators=[apps.ors.validators.validate_cedula]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ors.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='ors.deliveryman'),
        ),
    ]
