# Generated by Django 4.2 on 2023-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0008_alter_customer_cedula_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_per_pizza', models.FloatField()),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
