# Generated by Django 4.2 on 2023-05-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0010_alter_pizza_mass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='mass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ors.mass'),
        ),
    ]
