# Generated by Django 4.2 on 2023-05-14 02:17

import apps.ors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0011_alter_pizza_mass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_pizza',
            field=models.FloatField(validators=[apps.ors.validators.validate_price]),
        ),
        migrations.AlterField(
            model_name='mass',
            name='price_per_pizza',
            field=models.FloatField(validators=[apps.ors.validators.validate_price]),
        ),
    ]
