# Generated by Django 4.2 on 2023-05-20 22:31

import apps.ors.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0012_alter_ingredient_price_per_pizza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cedula',
            field=models.PositiveIntegerField(unique=True, validators=[apps.ors.validators.validate_cedula]),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='cedula',
            field=models.PositiveIntegerField(unique=True, validators=[apps.ors.validators.validate_cedula]),
        ),
    ]
