# Generated by Django 4.2 on 2023-05-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0013_alter_customer_cedula_alter_deliveryman_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryman',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
