# Generated by Django 4.2 on 2023-04-04 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cedula', models.PositiveIntegerField(help_text='La cédula debe contener 10 dígitos', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deliveryman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cedula', models.PositiveIntegerField(help_text='La cédula debe contener 10 dígitos', validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('stars', models.FloatField(default=0)),
                ('ratings_counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_per_pizza', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.deliveryman')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Median'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2)),
                ('mass_type', models.CharField(choices=[('NORMAL', 'Normal'), ('INTEGRAL', 'Integral'), ('EDUARDOS CHEESE', 'Eduardos Cheese')], max_length=15)),
                ('price', models.FloatField(default=0)),
                ('ingredients', models.ManyToManyField(to='webapp.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('NEQUI', 'Nequi')], max_length=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('domicile_price', models.PositiveIntegerField(default=8000)),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
                ('deliveryman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.deliveryman')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.pizza')),
            ],
        ),
    ]
