# Generated by Django 4.2 on 2023-04-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.deliveryman'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.customer'),
        ),
    ]
