# Generated by Django 4.2 on 2023-04-05 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_order_customer_info_alter_order_deliveryman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryman',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='deliveryman',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Deliveryman',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
